// <copyright file="AssemblyInfo.cs" company="Zizhen Li">
// Copyright (c) 2019 - 2020 Zizhen Li. All rights reserved.
// Licensed under the LGPL-3.0-only license. See LICENSE.md file in the project root for full license information.
// </copyright>

using System.Runtime.CompilerServices;
// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

[assembly: InternalsVisibleTo("RPG_Inventory_Remake.Tests")]
[assembly: InternalsVisibleTo("RPG_Inventory_Remake.Explorables")]
[assembly: InternalsVisibleTo("RPG_Inventory_Remake.Tests1")]
