// <copyright file="GlobalSuppressions.cs" company="Zizhen Li">
// Copyright (c) 2019 - 2020 Zizhen Li. All rights reserved.
// Licensed under the LGPL-3.0-only license. See LICENSE.md file in the project root for full license information.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake_Common.OutfitDatabase_TryDelete.Postfix(RimWorld.Outfit,Verse.AcceptanceReport)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "type", Target = "~T:RPG_Inventory_Remake_Common.OutfitDatabase_TryDelete")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake_Common.Pawn_OutfitTracker_CurrentOutfit.Postfix(RimWorld.Outfit,RimWorld.Pawn_OutfitTracker)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.JobGiver_RPGI_FindWeapon.TryGiveJob(Verse.Pawn)~Verse.AI.Job")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.JobGiver_FindItemByRadius`1.ValidateExceptStuff(Verse.Thing,RPG_Inventory_Remake.Loadout.ThingFilterAll)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.JobGiver_FindItemByRadius`1.Validate(Verse.Thing,RPG_Inventory_Remake.Loadout.ThingFilterAll)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.Jobs.JobGiver_RPGI_OpportunisticHaul.TryGiveJob(Verse.Pawn)~Verse.AI.Job")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.Loadout.RPGILoadout.Equals(RPG_Inventory_Remake.Loadout.RPGILoadout)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.Loadout.RPGILoadout.Equals(RPG_Inventory_Remake.Loadout.RPGILoadout)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.Loadout.compRPGILoudout.NotifiedAdded(Verse.Thing)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.Loadout.compRPGILoudout.NotifiedRemoved(Verse.Thing)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2211:Non-constant fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:RPG_Inventory_Remake.JobGiver_FindItemByRadius`1._radius")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~P:RPG_Inventory_Remake.JobGiver_FindItemByRadius`1.Radius")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.Loadout.compRPGILoudout.RPGIDebug.DebugNotifiedMethod(Verse.Pawn,Verse.Thing,RPG_Inventory_Remake.Loadout.RPGILoadout,System.Collections.Generic.Dictionary{Verse.Thing,System.Int32})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.JobDriver_Cleanup_RPGI_Patch.Postfix(Verse.AI.JobCondition,Verse.AI.JobDriver)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.JobGiver_FindItemByRadius`1.Reset")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2211:Non-constant fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:RPG_Inventory_Remake.JobGiver_FindItemByRadius`1._defaultRadiusIndex")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2211:Non-constant fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:RPG_Inventory_Remake.JobGiver_FindItemByRadius`1._lastRadiusIndex")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:RPG_Inventory_Remake.Loadout.RPGILoadout.UpdateItem(Verse.Thing,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1043:Use Integral Or String Argument For Indexers", Justification = "<Pending>", Scope = "member", Target = "~P:RPG_Inventory_Remake_Common.UnitTest.RPGIIntegrationTest.Item(System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1043:Use Integral Or String Argument For Indexers", Justification = "<Pending>", Scope = "member", Target = "~P:RPG_Inventory_Remake_Common.UnitTest.IntegrationTestHandler.Item(System.Type)")]
