//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGIResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG_Inventory_Remake.Resources.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmorBlunt.
        /// </summary>
        public static string ArmorBlunt {
            get {
                return ResourceManager.GetString("ArmorBlunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmorHeat.
        /// </summary>
        public static string ArmorHeat {
            get {
                return ResourceManager.GetString("ArmorHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmorSharp.
        /// </summary>
        public static string ArmorSharp {
            get {
                return ResourceManager.GetString("ArmorSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandy_Ascetic.
        /// </summary>
        public static string AsceticTab {
            get {
                return ResourceManager.GetString("AsceticTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_ChooseMaterialAndQuality.
        /// </summary>
        public static string ChooseMaterialAndQuality {
            get {
                return ResourceManager.GetString("ChooseMaterialAndQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComfyTemperatureRange.
        /// </summary>
        public static string ComfyTemperatureRange {
            get {
                return ResourceManager.GetString("ComfyTemperatureRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_CopyLoadout.
        /// </summary>
        public static string CopyLoadout {
            get {
                return ResourceManager.GetString("CopyLoadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_CountFieldTip.
        /// </summary>
        public static string CountFieldTip {
            get {
                return ResourceManager.GetString("CountFieldTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_Customize.
        /// </summary>
        public static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_DeleteLoadout.
        /// </summary>
        public static string DeleteLoadout {
            get {
                return ResourceManager.GetString("DeleteLoadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_DragToReorder.
        /// </summary>
        public static string DragToReorder {
            get {
                return ResourceManager.GetString("DragToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandy_Greedy.
        /// </summary>
        public static string GreedyTab {
            get {
                return ResourceManager.GetString("GreedyTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandy_Jealous.
        /// </summary>
        public static string JealousTab {
            get {
                return ResourceManager.GetString("JealousTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SandyMassCarried.
        /// </summary>
        public static string MassCarried {
            get {
                return ResourceManager.GetString("MassCarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_MouseOverNumbersForDetails.
        /// </summary>
        public static string MouseOverNumbersForDetails {
            get {
                return ResourceManager.GetString("MouseOverNumbersForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_NewLoadout.
        /// </summary>
        public static string NewLoadout {
            get {
                return ResourceManager.GetString("NewLoadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_NoLoadouts.
        /// </summary>
        public static string NoLoadouts {
            get {
                return ResourceManager.GetString("NoLoadouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_NoLoadoutSelected.
        /// </summary>
        public static string NoLoadoutSelected {
            get {
                return ResourceManager.GetString("NoLoadoutSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_NoMaterial.
        /// </summary>
        public static string NoMaterial {
            get {
                return ResourceManager.GetString("NoMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_OpenLoadout.
        /// </summary>
        public static string OpenLoadout {
            get {
                return ResourceManager.GetString("OpenLoadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_SelectLoadout.
        /// </summary>
        public static string SelectLoadout {
            get {
                return ResourceManager.GetString("SelectLoadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_SourceAllTip.
        /// </summary>
        public static string SourceAllTip {
            get {
                return ResourceManager.GetString("SourceAllTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparel.
        /// </summary>
        public static string SourceApparelTip {
            get {
                return ResourceManager.GetString("SourceApparelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_SourceFilterTip.
        /// </summary>
        public static string SourceFilterTip {
            get {
                return ResourceManager.GetString("SourceFilterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_SourceGenericTip.
        /// </summary>
        public static string SourceGenericTip {
            get {
                return ResourceManager.GetString("SourceGenericTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_SourceMeleeTip.
        /// </summary>
        public static string SourceMeleeTip {
            get {
                return ResourceManager.GetString("SourceMeleeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_SourceMinifiedTip.
        /// </summary>
        public static string SourceMinifiedTip {
            get {
                return ResourceManager.GetString("SourceMinifiedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_SourceRangedTip.
        /// </summary>
        public static string SourceRangedTip {
            get {
                return ResourceManager.GetString("SourceRangedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAAAAAAAAA.
        /// </summary>
        public static string TenCharsString {
            get {
                return ResourceManager.GetString("TenCharsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits.
        /// </summary>
        public static string Traits {
            get {
                return ResourceManager.GetString("Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corgi_Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
