//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Inventory_Remake_Common.UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwesomeInventory.Common.UnitTest.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Expected : {1}, Actual: {2}.
        /// </summary>
        public static string ExpectedString {
            get {
                return ResourceManager.GetString("ExpectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotooShabby.Rimworld.UnitTest.
        /// </summary>
        public static string HarmonyInstance {
            get {
                return ResourceManager.GetString("HarmonyInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       .
        /// </summary>
        public static string Indent {
            get {
                return ResourceManager.GetString("Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string KeyValuePair {
            get {
                return ResourceManager.GetString("KeyValuePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument has more one flag.
        /// </summary>
        public static string MoreThanOneFlag {
            get {
                return ResourceManager.GetString("MoreThanOneFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of children tests of {0} is {1}.
        /// </summary>
        public static string NumberOfChildrenTests {
            get {
                return ResourceManager.GetString("NumberOfChildrenTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Count.
        /// </summary>
        public static string ObjectCount {
            get {
                return ResourceManager.GetString("ObjectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} and {2}: {3} are not equal.
        /// </summary>
        public static string ObjectsAreNotEqual {
            get {
                return ResourceManager.GetString("ObjectsAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting TestFlag.Zero has no effect.
        /// </summary>
        public static string SettingFlagZero {
            get {
                return ResourceManager.GetString("SettingFlagZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1}.
        /// </summary>
        public static string ThingHas {
            get {
                return ResourceManager.GetString("ThingHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of total tests is {0}.
        /// </summary>
        public static string TotalTests {
            get {
                return ResourceManager.GetString("TotalTests", resourceCulture);
            }
        }
    }
}
